version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@nrwl/**" # we need to use nx migrate instead
    open-pull-requests-limit: 3
    

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
